### ISSUE TITLE
gspcore.f: kernel calculation

### ISSUE THREAD

**Issue by t-pollington** [frajaroco/mvstpp#7]
Dear @frajaroco,

Please could you help me in understanding the application of the kernel function _k_epsilon_ regarding the spatial and temporal mark variograms as described in equations 7 and 8 (p129) of your [_Mark variograms for spatio-temporal point processes paper_](https://www.sciencedirect.com/science/article/pii/S2211675317300696)  and how it relates to your code in [`gspcore.f`](https://github.com/frajaroco/mvstpp/blob/master/src/gspcore.f) as an example?

This is my current understanding however it results in a contradiction.

1) Is the _0 < epsilon < r_ condition only for the edge-corrections and so only applies to the "`standardised`" approach, or does it also apply to the "`simplified`" approach too? I think it may be the latter since on [`line 79`](https://github.com/frajaroco/mvstpp/blob/master/R/gsp.R) you drop the first element of `ds` which would be set to `hs`. I think this is because you want to avoid the _epsilon_(`hs`)=_r_(`ds`) case.

2) for the kernel function _k_epsilon(||x_i-x_j|| - r)_ I presume that only an argument "`x`"(say) greater than or equal to _r_ ( i.e. _x >= r_) is possible. But on [`lines 31-35`](https://github.com/frajaroco/mvstpp/blob/master/src/gspcore.f)
you divide `s(iu)-hij` by `hs`(i.e. _epsilon_). But if you divide the argument `x` by something that has to be smaller than _r_ (from 1 above as _0 < epsilon < r_) then this will result in an argument larger than 1. So when the kernel function runs e.g. `lines 90-104` then it will never run the `if` condition, only the `else`.

Kind regards, 

@t-pollington.

**Comment by frajaroco** [comment]
Dear @t-pollington, 

You questions about of reason the accommodation of the kernel function in the estimators of the spatial and temporal mark variograms can be solve if you take time to check the classical literature of the spatial point patterns. I recommend you read the following books in order to understand the geometry of the counts behind the estimators and it relationship with the kernel function and bandwints: 

1. [Statistical Analysis of Spatial and Spatio-Temporal Point Patterns](https://www.crcpress.com/Statistical-Analysis-of-Spatial-and-Spatio-Temporal-Point-Patterns/Diggle/p/book/9781466560239)
2. [Spatial Point Patterns: Methodology and Applications with R](https://www.crcpress.com/Spatial-Point-Patterns-Methodology-and-Applications-with-R/Baddeley-Rubak-Turner/p/book/9781482210200)
3. [Statistical Analysis and Modelling of Spatial Point Patterns](https://onlinelibrary.wiley.com/doi/book/10.1002/9780470725160)

If you are interested in more details or some kind of scientific cooperation please contact with me at the email frrodriguezc@unal.edu.co.

Regards!

**Comment by t-pollington** [comment]
Dear @frajaroco,

Thank you for the book references.

2. My second question is resolved! I realise that kernel functions can have negative arguments since they are symmetric.

1. I am still puzzled by the _0<epsilon<r_ condition in your paper and its purpose. If anything, for the Epanechnikov kernel, one needs _epsilon<0.5*(ds[i]-ds[i-1])_, assuming there are evenly spread `ds[i]`, to prevent overlap of pairs selected for adjacent `ds[i-1]`,`ds[i]`,`ds[i+1]`.

Yes let's discuss more. I'll be attending Spatial Statistics 2019 and hope to discuss more with you then on topics that interest us.

Kind regards, @t-pollington.
